spring.application.name=aep

# Configurações de Conexão com o PostgreSQL do Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/ecoculture
spring.datasource.username=eco_user
spring.datasource.password=eco_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
# update: Cria as tabelas automaticamente se não existirem e atualiza se você mudar as Models
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect